name: Java CI with PostgreSQL

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: senha123
          POSTGRES_DB: meu_banco
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U admin -d meu_banco"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5433 -U admin -d meu_banco; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Build & Run Tests
        env:
          DB_HOST: localhost
          DB_PORT: 5433
          DB_NAME: meu_banco
          DB_USER: admin
          DB_PASS: senha123
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/meu_banco
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: senha123
        run: mvn -B clean test
